language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.6
    - os: linux
      dist: trusty
      python: 3.5
    - os: osx
      osx_image: xcode7.2
      language: generic
      env: TOXenv=py36


before_script:
  - git submodule init
  - git submodule update

script:
  - python3 ./argparser.py --wasm ./test/injected.wasm
