language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.6
    - os: linux
      dist: trusty
      python: 3.5
    - os: linux
      dist: trusty
      python: 3.4
    - os: osx
      osx_image: xcode7.2
      language: generic
      before_install:
        - brew install python3


before_script:
  - git submodule init
  - git submodule update

script:
  - python3 ./argparser.py --wasm ./test/injected.wasm

after_success:
  - echo
